// Generated by gencpp from file loadcell-calibration/GetFactor.msg
// DO NOT EDIT!


#ifndef LOADCELL-CALIBRATION_MESSAGE_GETFACTOR_H
#define LOADCELL-CALIBRATION_MESSAGE_GETFACTOR_H

#include <ros/service_traits.h>


#include <loadcell-calibration/GetFactorRequest.h>
#include <loadcell-calibration/GetFactorResponse.h>


namespace loadcell-calibration
{

struct GetFactor
{

typedef GetFactorRequest Request;
typedef GetFactorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFactor
} // namespace loadcell-calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::loadcell-calibration::GetFactor > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::loadcell-calibration::GetFactor&) { return value(); }
};

template<>
struct DataType< ::loadcell-calibration::GetFactor > {
  static const char* value()
  {
    return "loadcell-calibration/GetFactor";
  }

  static const char* value(const ::loadcell-calibration::GetFactor&) { return value(); }
};


// service_traits::MD5Sum< ::loadcell-calibration::GetFactorRequest> should match 
// service_traits::MD5Sum< ::loadcell-calibration::GetFactor > 
template<>
struct MD5Sum< ::loadcell-calibration::GetFactorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::loadcell-calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell-calibration::GetFactorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::loadcell-calibration::GetFactorRequest> should match 
// service_traits::DataType< ::loadcell-calibration::GetFactor > 
template<>
struct DataType< ::loadcell-calibration::GetFactorRequest>
{
  static const char* value()
  {
    return DataType< ::loadcell-calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell-calibration::GetFactorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::loadcell-calibration::GetFactorResponse> should match 
// service_traits::MD5Sum< ::loadcell-calibration::GetFactor > 
template<>
struct MD5Sum< ::loadcell-calibration::GetFactorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::loadcell-calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell-calibration::GetFactorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::loadcell-calibration::GetFactorResponse> should match 
// service_traits::DataType< ::loadcell-calibration::GetFactor > 
template<>
struct DataType< ::loadcell-calibration::GetFactorResponse>
{
  static const char* value()
  {
    return DataType< ::loadcell-calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell-calibration::GetFactorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOADCELL-CALIBRATION_MESSAGE_GETFACTOR_H
