// Generated by gencpp from file loadcell_calibration/GetFactorRequest.msg
// DO NOT EDIT!


#ifndef LOADCELL_CALIBRATION_MESSAGE_GETFACTORREQUEST_H
#define LOADCELL_CALIBRATION_MESSAGE_GETFACTORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace loadcell_calibration
{
template <class ContainerAllocator>
struct GetFactorRequest_
{
  typedef GetFactorRequest_<ContainerAllocator> Type;

  GetFactorRequest_()
    : lbs_reading(0.0)  {
    }
  GetFactorRequest_(const ContainerAllocator& _alloc)
    : lbs_reading(0.0)  {
    }



   typedef double _lbs_reading_type;
  _lbs_reading_type lbs_reading;




  typedef boost::shared_ptr< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFactorRequest_

typedef ::loadcell_calibration::GetFactorRequest_<std::allocator<void> > GetFactorRequest;

typedef boost::shared_ptr< ::loadcell_calibration::GetFactorRequest > GetFactorRequestPtr;
typedef boost::shared_ptr< ::loadcell_calibration::GetFactorRequest const> GetFactorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loadcell_calibration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f0e6a96bd902d97b0033da431e3f2f6";
  }

  static const char* value(const ::loadcell_calibration::GetFactorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f0e6a96bd902d97ULL;
  static const uint64_t static_value2 = 0xb0033da431e3f2f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loadcell_calibration/GetFactorRequest";
  }

  static const char* value(const ::loadcell_calibration::GetFactorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lbs_reading\n\
";
  }

  static const char* value(const ::loadcell_calibration::GetFactorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lbs_reading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetFactorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loadcell_calibration::GetFactorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loadcell_calibration::GetFactorRequest_<ContainerAllocator>& v)
  {
    s << indent << "lbs_reading: ";
    Printer<double>::stream(s, indent + "  ", v.lbs_reading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOADCELL_CALIBRATION_MESSAGE_GETFACTORREQUEST_H
