// Generated by gencpp from file loadcell_calibration/GetFactor.msg
// DO NOT EDIT!


#ifndef LOADCELL_CALIBRATION_MESSAGE_GETFACTOR_H
#define LOADCELL_CALIBRATION_MESSAGE_GETFACTOR_H

#include <ros/service_traits.h>


#include <loadcell_calibration/GetFactorRequest.h>
#include <loadcell_calibration/GetFactorResponse.h>


namespace loadcell_calibration
{

struct GetFactor
{

typedef GetFactorRequest Request;
typedef GetFactorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFactor
} // namespace loadcell_calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::loadcell_calibration::GetFactor > {
  static const char* value()
  {
    return "dc5041cd9b38a6c10e3ab905f7b1c263";
  }

  static const char* value(const ::loadcell_calibration::GetFactor&) { return value(); }
};

template<>
struct DataType< ::loadcell_calibration::GetFactor > {
  static const char* value()
  {
    return "loadcell_calibration/GetFactor";
  }

  static const char* value(const ::loadcell_calibration::GetFactor&) { return value(); }
};


// service_traits::MD5Sum< ::loadcell_calibration::GetFactorRequest> should match 
// service_traits::MD5Sum< ::loadcell_calibration::GetFactor > 
template<>
struct MD5Sum< ::loadcell_calibration::GetFactorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::loadcell_calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell_calibration::GetFactorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::loadcell_calibration::GetFactorRequest> should match 
// service_traits::DataType< ::loadcell_calibration::GetFactor > 
template<>
struct DataType< ::loadcell_calibration::GetFactorRequest>
{
  static const char* value()
  {
    return DataType< ::loadcell_calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell_calibration::GetFactorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::loadcell_calibration::GetFactorResponse> should match 
// service_traits::MD5Sum< ::loadcell_calibration::GetFactor > 
template<>
struct MD5Sum< ::loadcell_calibration::GetFactorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::loadcell_calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell_calibration::GetFactorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::loadcell_calibration::GetFactorResponse> should match 
// service_traits::DataType< ::loadcell_calibration::GetFactor > 
template<>
struct DataType< ::loadcell_calibration::GetFactorResponse>
{
  static const char* value()
  {
    return DataType< ::loadcell_calibration::GetFactor >::value();
  }
  static const char* value(const ::loadcell_calibration::GetFactorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOADCELL_CALIBRATION_MESSAGE_GETFACTOR_H
