// Generated by gencpp from file loadcell-calibration/GetFactorResponse.msg
// DO NOT EDIT!


#ifndef LOADCELL-CALIBRATION_MESSAGE_GETFACTORRESPONSE_H
#define LOADCELL-CALIBRATION_MESSAGE_GETFACTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace loadcell-calibration
{
template <class ContainerAllocator>
struct GetFactorResponse_
{
  typedef GetFactorResponse_<ContainerAllocator> Type;

  GetFactorResponse_()
    : sum(0)  {
    }
  GetFactorResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
    }



   typedef int64_t _sum_type;
  _sum_type sum;




  typedef boost::shared_ptr< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFactorResponse_

typedef ::loadcell-calibration::GetFactorResponse_<std::allocator<void> > GetFactorResponse;

typedef boost::shared_ptr< ::loadcell-calibration::GetFactorResponse > GetFactorResponsePtr;
typedef boost::shared_ptr< ::loadcell-calibration::GetFactorResponse const> GetFactorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loadcell-calibration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::loadcell-calibration::GetFactorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loadcell-calibration/GetFactorResponse";
  }

  static const char* value(const ::loadcell-calibration::GetFactorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n\
\n\
";
  }

  static const char* value(const ::loadcell-calibration::GetFactorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetFactorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loadcell-calibration::GetFactorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loadcell-calibration::GetFactorResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOADCELL-CALIBRATION_MESSAGE_GETFACTORRESPONSE_H
